USE bibliotheque;

SET FOREIGN_KEY_CHECKS=0;

CREATE TABLE IF NOT EXISTS BOOK (
    book_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    book_name VARCHAR(150) NOT NULL,
    book_author VARCHAR(100) NOT NULL,
    book_date DATE,
    book_editor VARCHAR(100),
    book_image_ext VARCHAR(100)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS RIGHTS (
    right_id SMALLINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    right_name VARCHAR(50) NOT NULL UNIQUE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS ROLES (
    role_id TINYINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    role_name VARCHAR(50) NOT NULL UNIQUE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS ROLE_RIGHTS (
    role_id TINYINT UNSIGNED NOT NULL,
    right_id SMALLINT UNSIGNED NOT NULL,
    PRIMARY KEY (role_id, right_id),
    FOREIGN KEY (role_id) REFERENCES ROLES(role_id),
    FOREIGN KEY (right_id) REFERENCES RIGHTS(right_id)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS USERS (
    user_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_pswd VARCHAR(255) NOT NULL,
    user_name VARCHAR(100) NOT NULL,
    user_mail VARCHAR(150) NOT NULL UNIQUE,
    role_id TINYINT UNSIGNED NOT NULL,
    FOREIGN KEY (role_id) REFERENCES ROLES(role_id)
) ENGINE=InnoDB;

CREATE TABLE LIBRARY_STOCK (
    book_id INT UNSIGNED PRIMARY KEY,
    total_stock INT UNSIGNED NOT NULL DEFAULT 1,
    borrowed_count INT UNSIGNED NOT NULL DEFAULT 0,
    FOREIGN KEY (book_id) REFERENCES BOOK(book_id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE BORROWED (
    id_borrow INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    user_id INT UNSIGNED NOT NULL,
    book_id INT UNSIGNED NOT NULL,
    date_start DATE NOT NULL,
    date_end DATE NOT NULL,
    is_returned TINYINT(1) DEFAULT 0,
    FOREIGN KEY (user_id) REFERENCES USERS(user_id) ON DELETE CASCADE,
    FOREIGN KEY (book_id) REFERENCES BOOK(book_id) ON DELETE CASCADE, -- ← AJOUTÉ !
    INDEX idx_active_borrow (user_id, book_id, is_returned)
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS DELAY (
    delay_id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    borrow_id INT UNSIGNED NOT NULL,
    delay_time INT NOT NULL,
    FOREIGN KEY (borrow_id) REFERENCES BORROWED(id_borrow)
) ENGINE=InnoDB;

SET FOREIGN_KEY_CHECKS=1;
